apiVersion: v1
kind: Service
metadata:
  labels:
    app: selfcare-survey
  name: selfcare-survey
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: "selfcare-survey-service"
    port: 8081
    targetPort: 8081
  selector:
    app: selfcare-survey
